### ISSUE TITLE
semgrep extention is not showing their features

### ISSUE THREAD

**Issue by Kasireddy-venkateswarlu** [gand3lf/semgrepper#12]
Hi as soon as i loaded exetention in burp it does not showing any features other than error message

"It seems that you don't have Semgrep installed!

Please, follow these instructions to install it:
 • Ubuntu, Windows through Windows Subsystem for Linux (WSL), Linux, macOS:
     python3 -m pip install semgrep
 • macOS:
     brew install semgrep"

i have already installed semgrep in kali linux 

semgrep --version
1.122.0

**Comment by gand3lf** [comment]
Hi!
Could you please show me the result of the "which semgrep" command? It
could be possible that semgrep is not inside the PATH environment variable
in use by the Java extension.

Thank you,
Riccardo Cardelli

Il giorno ven 23 mag 2025 alle ore 11:14 Kasireddy-venkateswarlu <
***@***.***> ha scritto:

**Comment by Kasireddy-venkateswarlu** [comment]
Here is the output 

which semgrep
/home/kasi/.local/bin/semgrep

**Comment by gand3lf** [comment]
Hi,
I have pushed a solution right now on my repo:
https://github.com/gand3lf/semgrepper
Please could you check if this new solution works?

Thank you,
Riccardo Cardelli


Il giorno ven 23 mag 2025 alle ore 12:20 Kasireddy-venkateswarlu <
***@***.***> ha scritto:

**Comment by Kasireddy-venkateswarlu** [comment]
Hi , 

it is not working, still getting same error.(downloaded updated extension from https://github.com/gand3lf/semgrepper/releases/tag/v1.4)
 However i can able to use this extension by launching burp suite from terminal.

![Image](https://github.com/user-attachments/assets/e885022f-a3c3-4f5c-a99b-c2826fce7908)

Regards,
Kasireddy

**Comment by Kasireddy-venkateswarlu** [comment]
Can you please tell me which Semgrep rules I can use to detect any kind of client-side encryption, encoding, or validation logic in JavaScript?

**Comment by gand3lf** [comment]
Sure! You can download the public semgrep rules in the official repository:
- https://github.com/semgrep/semgrep-rules

Then you can Import the rules in the "Rules Files" section. Please note
that you can add the entire "javascript" directory and the extension will
automatically select the correct rule files. Then press "Current Semgrepper
is off" button to activate the extension. Then you can launch a passive
scan on the specific target.

Il giorno ven 23 mag 2025 alle ore 14:47 Kasireddy-venkateswarlu <
***@***.***> ha scritto:
